#!/usr/bin/env node

/**
 * GeoTech SpareFinder - Environment Setup Script
 * 
 * This script helps configure the environment variables for both
 * the frontend and AI service to work together.
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

console.log('🚀 GeoTech SpareFinder - Environment Setup');
console.log('============================================');
console.log('This script will help you configure the environment for the AI service.\n');

// Frontend .env.local content
const frontendEnvContent = `# GeoTech SpareFinder - Frontend Environment
# Generated by setup script

# =============================================
# REQUIRED - Application will not work without these
# =============================================

# AI Service Configuration (REQUIRED)
VITE_AI_SERVICE_URL=http://localhost:8000
VITE_AI_SERVICE_API_KEY=geotech-dev-key-2024

# Application Configuration
VITE_APP_URL=http://localhost:5173
VITE_APP_NAME="GeoTech SpareFinder"

# Supabase Configuration (Update when you set up Supabase)
VITE_SUPABASE_URL=https://your-project.supabase.co
VITE_SUPABASE_ANON_KEY=your-supabase-anon-key

# =============================================
# DEVELOPMENT SETTINGS
# =============================================

# API Configuration
VITE_API_TIMEOUT=30000
VITE_MAX_FILE_SIZE=10485760
VITE_SUPPORTED_FORMATS=image/jpeg,image/png,image/webp

# Development & Debug
VITE_DEBUG=true
VITE_LOG_LEVEL=debug
NODE_ENV=development

# Security & CORS (for development)
VITE_ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000
VITE_CORS_ENABLED=true

# =============================================
# NOTES
# =============================================
# 1. The AI service should be running on localhost:8000
# 2. Update VITE_SUPABASE_* values when you set up Supabase
# 3. Use 'npm run dev' to start the frontend development server
# 4. Check AI service health: curl http://localhost:8000/health
`;

// AI Service .env content
const aiServiceEnvContent = `# AI Service Environment Configuration
# Generated by setup script for GeoTech SpareFinder

# =============================================
# REQUIRED - Application will not work without these
# =============================================

# API Authentication (Must match frontend)
API_KEY=geotech-dev-key-2024

# Server Configuration
HOST=0.0.0.0
PORT=8000
DEBUG=true
ENVIRONMENT=development

# CORS Configuration for frontend
ALLOWED_ORIGINS=http://localhost:5173,http://localhost:3000,http://localhost:8000
ALLOWED_HOSTS=localhost,127.0.0.1

# =============================================
# OPTIONAL - Database and External APIs
# =============================================

# Supabase Configuration (if using database features)
SUPABASE_URL=https://your-project.supabase.co
SUPABASE_KEY=your-supabase-anon-key

# Google Custom Search API (for enhanced part information)
# Get free API key at: https://console.developers.google.com/
GOOGLE_API_KEY=your-google-api-key
GOOGLE_SEARCH_ENGINE_ID=your-search-engine-id

# Octopart/Nexar API (for part databases)
# Get free API key at: https://portal.nexar.com/
OCTOPART_API_KEY=your-octopart-api-key

# =============================================
# AI Model Configuration
# =============================================

# TensorFlow Model Settings
MODEL_PATH=/app/models/mobilenet_v2
MODEL_TYPE=mobilenet_v2
DEFAULT_CONFIDENCE_THRESHOLD=0.5

# Processing Limits
MAX_FILE_SIZE_MB=10
BATCH_SIZE_LIMIT=10
REQUEST_TIMEOUT=30

# =============================================
# Performance & Monitoring
# =============================================

LOG_LEVEL=INFO
METRICS_ENABLED=true
WORKER_PROCESSES=1
MAX_CONCURRENT_REQUESTS=100

# =============================================
# NOTES
# =============================================
# 1. This API_KEY must match the one used in the frontend
# 2. Update Supabase credentials if using database features
# 3. Add external API keys for enhanced part search capabilities
# 4. In production, use secure, environment-specific values
# 5. Start the service with: python ai-service/start.py
`;

async function askQuestion(question) {
    return new Promise((resolve) => {
        rl.question(question, (answer) => {
            resolve(answer.trim());
        });
    });
}

async function setupEnvironment() {
    try {
        console.log('📁 Setting up environment files...\n');

        // Create frontend .env.local
        const frontendEnvPath = path.join(__dirname, '.env.local');

        if (fs.existsSync(frontendEnvPath)) {
            const overwrite = await askQuestion('❓ Frontend .env.local already exists. Overwrite? (y/N): ');
            if (overwrite.toLowerCase() !== 'y') {
                console.log('⏭️  Skipping frontend environment setup...');
            } else {
                fs.writeFileSync(frontendEnvPath, frontendEnvContent);
                console.log('✅ Created frontend .env.local');
            }
        } else {
            fs.writeFileSync(frontendEnvPath, frontendEnvContent);
            console.log('✅ Created frontend .env.local');
        }

        // Create AI service .env
        const aiServiceEnvPath = path.join(__dirname, 'ai-service', '.env');

        if (fs.existsSync(aiServiceEnvPath)) {
            const overwrite = await askQuestion('❓ AI service .env already exists. Overwrite? (y/N): ');
            if (overwrite.toLowerCase() !== 'y') {
                console.log('⏭️  Skipping AI service environment setup...');
            } else {
                fs.writeFileSync(aiServiceEnvPath, aiServiceEnvContent);
                console.log('✅ Created AI service .env');
            }
        } else {
            fs.writeFileSync(aiServiceEnvPath, aiServiceEnvContent);
            console.log('✅ Created AI service .env');
        }

        console.log('\n🎉 Environment setup complete!');
        console.log('\n📋 Next Steps:');
        console.log('   1. Start the AI service: cd ai-service && python start.py');
        console.log('   2. In a new terminal, start the frontend: npm run dev');
        console.log('   3. Open http://localhost:5173 in your browser');
        console.log('   4. Test image upload on the Upload page');
        console.log('\n🔧 Optional Configuration:');
        console.log('   • Set up Supabase account and update SUPABASE_* variables');
        console.log('   • Get Google Custom Search API key for enhanced results');
        console.log('   • Get Octopart API key for part database access');
        console.log('\n📚 Documentation:');
        console.log('   • Check README.md for detailed setup instructions');
        console.log('   • Environment template: env.template');
        console.log('   • AI service docs: ai-service/README.md');

    } catch (error) {
        console.error('❌ Error setting up environment:', error.message);
        process.exit(1);
    } finally {
        rl.close();
    }
}

// Check if running as script
if (require.main === module) {
    setupEnvironment();
}

module.exports = { setupEnvironment };